name: Flybody
dname: fly_run
camera: 1
rendering_mjcf: ${paths.cwd_dir}/assets/fruitfly/fruitfly_force_fast.xml
stac_path: ${paths.data_dir}/transform_tethered.p
clip_idx: 0
env_args:
  clip_length: 1001
  mjcf_path: "${paths.cwd_dir}/assets/fruitfly/fruitfly_force_fast.xml" 
  physics_timestep: 2e-4
  solver: cg
  iterations: 6
  ls_iterations: 6
  torque_actuators: True
  physics_steps_per_control_step: 10
  tracking_lin_vel_weight: 5.5
  tracking_ang_vel_weight:  1
  lin_vel_z_weight: -2.0
  ang_vel_xy_weight: -0.05
  orientation_weight: -5.0
  torques_weight: -0.0002
  action_rate_weight: -0.01
  stand_still_weight: -0.5
  termination_weight: -1.0
  healthy_z_range: [-0.03, 0.1]
  reset_noise_scale: 1e-3
  ref_len: 5
  free_jnt: True
  inference_mode: False
  end_eff_names:
    - claw_T1_left
    - claw_T1_right
    - claw_T2_left
    - claw_T2_right
    - claw_T3_left
    - claw_T3_right
  body_names:
    - coxa_T1_left
    - femur_T1_left
    - tibia_T1_left
    - tarsus_T1_left
    - tarsus2_T1_left
    - tarsus3_T1_left
    - tarsus4_T1_left
    - claw_T1_left
    - coxa_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - tarsus2_T1_right
    - tarsus3_T1_right
    - tarsus4_T1_right
    - claw_T1_right
    - coxa_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - tarsus2_T2_left
    - tarsus3_T2_left
    - tarsus4_T2_left
    - claw_T2_left
    - coxa_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - tarsus2_T2_right
    - tarsus3_T2_right
    - tarsus4_T2_right
    - claw_T2_right
    - coxa_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - tarsus2_T3_left
    - tarsus3_T3_left
    - tarsus4_T3_left
    - claw_T3_left
    - coxa_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right
    - tarsus2_T3_right
    - tarsus3_T3_right
    - tarsus4_T3_right
    - claw_T3_right
  joint_names:
    - coxa_flexion_T1_left
    - coxa_twist_T1_left
    - femur_twist_T1_left
    - femur_T1_left
    - tibia_T1_left
    - tarsus_T1_left
    - coxa_flexion_T1_right
    - coxa_twist_T1_right
    - femur_twist_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - coxa_flexion_T2_left
    - coxa_twist_T2_left
    - femur_twist_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - coxa_flexion_T2_right
    - coxa_twist_T2_right
    - femur_twist_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - coxa_flexion_T3_left
    - coxa_twist_T3_left
    - femur_twist_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - coxa_flexion_T3_right
    - coxa_twist_T3_right
    - femur_twist_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right