name: Flybody
dname: fly_freejnt
camera: 1
rendering_mjcf: ${paths.cwd_dir}/assets/fruitfly/fruitfly_force_pair.xml
stac_path: ${paths.data_dir}/transform_tethered.p
clip_idx: 0
ref_traj_length: 5
env_args:
  clip_length: 1001
  mjcf_path: "${paths.cwd_dir}/assets/fruitfly/fruitfly_fast.xml" 
  scale_factor: 1 
  sim_timestep: 2e-4
  solver: cg
  iterations: 6
  ls_iterations: 6
  torque_actuators: False
  physics_steps_per_control_step: 10
  too_far_dist: 0.01
  bad_pose_dist: 3.0 # 60.0
  bad_quat_dist: 0.05 #1.25
  ctrl_cost_weight: -0.001
  pos_reward_weight: 1.0
  quat_reward_weight: 1.0
  joint_reward_weight: 1.0
  angvel_reward_weight: 0.5
  bodypos_reward_weight: 0.5
  endeff_reward_weight: 1.0
  termination_weight: -1.0
  pos_scaling: 400.0
  joint_scaling: 0.25
  angvel_scaling: 0.5
  bodypos_scaling: 8.0
  endeff_scaling: 500.0
  quat_scaling: 4.0
  healthy_reward: 1.0
  healthy_z_range: [-0.03, 0.1]
  reset_noise_scale: 1e-3
  terminate_when_unhealthy: True
  free_jnt: True
  inference_mode: False
  end_eff_names:
    - claw_T1_left
    - claw_T1_right
    - claw_T2_left
    - claw_T2_right
    - claw_T3_left
    - claw_T3_right
  appendage_names:
    - tarsus_T1_left
    - tarsus_T1_right
    - tarsus_T2_left
    - tarsus_T2_right
    - tarsus_T3_left
    - tarsus_T3_right
  body_names:
    - thorax
    - head
    - rostrum
    - haustellum
    - labrum_left
    - labrum_right
    - antenna_left
    - antenna_right
    - wing_left
    - wing_right
    - abdomen
    - abdomen_2
    - abdomen_3
    - abdomen_4
    - abdomen_5
    - abdomen_6
    - abdomen_7
    - haltere_left
    - haltere_right
    - coxa_T1_left
    - femur_T1_left
    - tibia_T1_left
    - tarsus_T1_left
    - tarsus2_T1_left
    - tarsus3_T1_left
    - tarsus4_T1_left
    - claw_T1_left
    - coxa_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - tarsus2_T1_right
    - tarsus3_T1_right
    - tarsus4_T1_right
    - claw_T1_right
    - coxa_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - tarsus2_T2_left
    - tarsus3_T2_left
    - tarsus4_T2_left
    - claw_T2_left
    - coxa_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - tarsus2_T2_right
    - tarsus3_T2_right
    - tarsus4_T2_right
    - claw_T2_right
    - coxa_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - tarsus2_T3_left
    - tarsus3_T3_left
    - tarsus4_T3_left
    - claw_T3_left
    - coxa_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right
    - tarsus2_T3_right
    - tarsus3_T3_right
    - tarsus4_T3_right
    - claw_T3_right
  site_names: 
    - tracking[coxa_T1_left]
    - tracking[femur_T1_left]
    - tracking[tibia_T1_left]
    - tracking[tarsus_T1_left]
    - tracking[claw_T1_left]
    - tracking[coxa_T1_right]
    - tracking[femur_T1_right]
    - tracking[tibia_T1_right]
    - tracking[tarsus_T1_right]
    - tracking[claw_T1_right]
    - tracking[coxa_T2_left]
    - tracking[femur_T2_left]
    - tracking[tibia_T2_left]
    - tracking[tarsus_T2_left]
    - tracking[claw_T2_left]
    - tracking[coxa_T2_right]
    - tracking[femur_T2_right]
    - tracking[tibia_T2_right]
    - tracking[tarsus_T2_right]
    - tracking[claw_T2_right]
    - tracking[coxa_T3_left]
    - tracking[femur_T3_left]
    - tracking[tibia_T3_left]
    - tracking[tarsus_T3_left]
    - tracking[claw_T3_left]
    - tracking[coxa_T3_right]
    - tracking[femur_T3_right]
    - tracking[tibia_T3_right]
    - tracking[tarsus_T3_right]
    - tracking[claw_T3_right]
  joint_names:
    - coxa_flexion_T1_left
    - coxa_twist_T1_left
    - femur_twist_T1_left
    - femur_T1_left
    - tibia_T1_left
    - tarsus_T1_left
    - coxa_flexion_T1_right
    - coxa_twist_T1_right
    - femur_twist_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - coxa_flexion_T2_left
    - coxa_twist_T2_left
    - femur_twist_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - coxa_flexion_T2_right
    - coxa_twist_T2_right
    - femur_twist_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - coxa_flexion_T3_left
    - coxa_twist_T3_left
    - femur_twist_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - coxa_flexion_T3_right
    - coxa_twist_T3_right
    - femur_twist_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right
  center_of_mass: thorax