name: Flybody
dname: fly_freejnt
camera: 1
rendering_mjcf: ${paths.cwd_dir}/assets/fruitfly/fruitfly_force_pair.xml
stac_path: ${paths.data_dir}/transform_mocap_fly_freejnt.p
clip_idx: 0
clip_length: 601
ref_traj_length: 15
env_args:
  mjcf_path: "${paths.cwd_dir}/assets/fruitfly/fruitfly_force_fast.xml" # add logic from vnl
  scale_factor: 1 # add logic from vnl
  solver: cg
  iterations: 6
  ls_iterations: 6
  torque_actuators: False
  physics_steps_per_control_step: 10
  too_far_dist: 0.1
  bad_pose_dist: 1000.0 # 60.0
  bad_quat_dist: 1000.0 #1.25
  ctrl_cost_weight: 0.01
  pos_reward_weight: 0
  quat_reward_weight: 1.0
  joint_reward_weight: 50.0
  angvel_reward_weight: 0.0
  bodypos_reward_weight: 1.0
  endeff_reward_weight: 1.0
  healthy_reward: 0.25
  healthy_z_range: [-0.05, 0.1]
  terminate_when_unhealthy: True
  free_jnt: True
  end_eff_names:
    - claw_T1_left
    - claw_T1_right
    - claw_T2_left
    - claw_T2_right
    - claw_T3_left
    - claw_T3_right
  appendage_names:
    - tarsus_T1_left
    - tarsus_T1_right
    - tarsus_T2_left
    - tarsus_T2_right
    - tarsus_T3_left
    - tarsus_T3_right
  body_names:
    - thorax
    - head
    - rostrum
    - haustellum
    - labrum_left
    - labrum_right
    - antenna_left
    - antenna_right
    - wing_left
    - wing_right
    - abdomen
    - abdomen_2
    - abdomen_3
    - abdomen_4
    - abdomen_5
    - abdomen_6
    - abdomen_7
    - haltere_left
    - haltere_right
    - coxa_T1_left
    - femur_T1_left
    - tibia_T1_left
    - tarsus_T1_left
    - tarsus2_T1_left
    - tarsus3_T1_left
    - tarsus4_T1_left
    - claw_T1_left
    - coxa_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - tarsus2_T1_right
    - tarsus3_T1_right
    - tarsus4_T1_right
    - claw_T1_right
    - coxa_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - tarsus2_T2_left
    - tarsus3_T2_left
    - tarsus4_T2_left
    - claw_T2_left
    - coxa_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - tarsus2_T2_right
    - tarsus3_T2_right
    - tarsus4_T2_right
    - claw_T2_right
    - coxa_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - tarsus2_T3_left
    - tarsus3_T3_left
    - tarsus4_T3_left
    - claw_T3_left
    - coxa_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right
    - tarsus2_T3_right
    - tarsus3_T3_right
    - tarsus4_T3_right
    - claw_T3_right
  joint_names:
    - coxa_flexion_T1_left
    - coxa_twist_T1_left
    - femur_T1_left
    - femur_twist_T1_left
    - tibia_T1_left
    - tarsus_T1_left
    - coxa_flexion_T1_right
    - coxa_twist_T1_right
    - femur_T1_right
    - femur_twist_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - coxa_flexion_T2_left
    - coxa_twist_T2_left
    - femur_T2_left
    - femur_twist_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - coxa_flexion_T2_right
    - coxa_twist_T2_right
    - femur_T2_right
    - femur_twist_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - coxa_flexion_T3_left
    - coxa_twist_T3_left
    - femur_T3_left
    - femur_twist_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - coxa_flexion_T3_right
    - coxa_twist_T3_right
    - femur_T3_right
    - femur_twist_T3_right
    - tibia_T3_right
    - tarsus_T3_right
  center_of_mass: thorax