name: Flybody
dname: fly_stand
camera: 1
rendering_mjcf: ${paths.cwd_dir}/assets/fruitfly/fruitfly_force_fast.xml
stac_path: ${paths.data_dir}/transform_mocap_fly_freejnt.p
clip_idx: 0
ref_traj_length: 15
env_args:
  clip_length: 1000
  mjcf_path: "${paths.cwd_dir}/assets/fruitfly/fruitfly_force_fastrun.xml" 
  ref_path: ${paths.data_dir}/clips/0_stand.h5
  sim_timestep: 2e-4
  solver: cg
  iterations: 6
  ls_iterations: 6
  physics_steps_per_control_step: 10
  ctrl_cost_weight: 0.01
  forward_reward_weight: 0
  tracking_lin_vel_weight: 0
  lin_vel_z_weight: -2.0
  ang_vel_xy_weight: -0.05
  orientation_weight: -1.0
  torques_weight: -0.0002
  action_rate_weight: -0.01
  stand_still_weight: -0.5
  termination_weight: -1.0
  healthy_reward: 5.0
  healthy_z_range: [-0.02, 0.1]
  terminate_when_unhealthy: True
  free_jnt: True
  inference_mode: False
  center_of_mass: thorax
  